spring:
  profiles:
    active: dev, base-addi
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: info
    com.ll.comibird.Week_Mission.app: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  site:
    name: Ebook
    baseUrl: "http://localhost:8010"