spring:
  datasource:
    url: jdbc:mariadb://t2.yejin.site:3306/wbook_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: yejin
    password: yejin1234
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com.ll.exam.wbook: info
#custom:
#  genFileDirPath: /gen